### ISSUE TITLE
Channel?

### ISSUE THREAD

**Issue by boss69xd** [BullyWiiPlaza/tcpgecko#19]
Could you make a wii u menu channel for TCPGecko like the WUP Installer GX2? That would be very convenient.

**Comment by BullyWiiPlaza** [comment]
If you use CHBC and boot into the HBL on launch of the Wii U, you can load the app quickly as well. It's fine.

**Comment by boss69xd** [comment]
But can you make a wii u menu channel for it easy? or is it hard?
