### ISSUE TITLE
BOTW Update Causes Crashes

### ISSUE THREAD

**Issue by sephirothrr** [BullyWiiPlaza/tcpgecko#2]
I'm not sure if this also has to do with the recent minor fixes, but since the recent Breath of the Wild Update, trying to connect via TCPGecko causes a crash with an  "exception type DSI occurred" error. If it'll help, I can try to trigger the error again to get what appears to be some sort of memory dump information.

**Comment by joffnerd** [comment]
This isn't anything to do with Bully, please don't post here about it. It was clearly an update to the game breaking things...

**Comment by BullyWiiPlaza** [comment]
True, I was about to say that. Kinda pointless...
