### ISSUE TITLE
i can`t do 

### ISSUE THREAD

**Issue by ALittleHacker** [BullyWiiPlaza/tcpgecko#20]
![image](https://user-images.githubusercontent.com/39169889/39889115-4c79483c-546d-11e8-8761-0a0638e8954a.png)

**Comment by BullyWiiPlaza** [comment]
This is a JGecko U bug but you're running an old version. Please download the newest one from here:
https://github.com/BullyWiiPlaza/JGeckoU/blob/master/JGecko%20U.jar?raw=true

**Comment by ALittleHacker** [comment]
Thank you for your help :)
