### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by WoomyKing7** [BullyWiiPlaza/tcpgecko#21]
I follow the guides exactly, but every time I try to connect my JGecko U to my Wii U crashes.
The error message is:
Illegal command byte received: 0x84
Server Version: 03/30/2017

**Comment by BullyWiiPlaza** [comment]
If you used your brain then maybe you realized the server version is too old. It's even printed right there. You didn't even bother downloading the .elf from this repository but opened an issue. Major fail.
