### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by wildfirebill** [BullyWiiPlaza/tcpgecko#23]
![jgeckouerror](https://user-images.githubusercontent.com/8473557/42351182-b4facd50-8081-11e8-8d68-8761464f2818.PNG)
dont know what I'm doing wrong I followed your video on installing dev jdk.
downloaded tcpgecko.elf
ran it with A no sd cheats
opened by homebrew browser installed
started game then waited for graphics to load and clicked connect
Twilight Princess HD
windows 7 ultimate
64x

**Comment by wildfirebill** [comment]
troubleshooting started on wii u home menu and it connected then started game. diffrent error added screenshot
![wiiuerror](https://user-images.githubusercontent.com/8473557/42351509-4cd8f48e-8083-11e8-9cbd-9c3ff91e0993.PNG)

**Comment by BullyWiiPlaza** [comment]
You have to reconnect if a new title (a.k.a. game) is loaded. These errors are common if 1) it fails to connect and 2) if it tries to write and the connection is broken because you switched titles or it crashed. So what's your problem now?
